services:
  - type: web
    name: mojiza-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python runer.py run_script
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    autoDeploy: true
    plan: free
    region: oregon
