services:
  - type: web
    name: mojiza-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python runer.py run_script -n $PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    region: oregon
